name: Lint, Tests and Typecheck

on:
  pull_request:
    branches:
      - "**"

env:
  # Disable Next telemetry
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      - name: Install Dependencies
        run: bun install
      - name: Code check
        run: |
          bun run lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      - name: Install Dependencies
        run: bun install
      - name: Code check
        run: |
          bun run test
